### ISSUE TITLE
Incompatible with flake8 version 3

### ISSUE THREAD

**Issue by xZise** [zheller/flake8-quotes#29]
There is a beta version of flake8 version 3, which doesn't use `config_options` anymore so I get the following error:

```
Traceback (most recent call last):
  File "/home/xzise/.pyenv/versions/3.5.1/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/application.py", line 293, in run
    self._run(argv)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/application.py", line 279, in _run
    self.initialize(argv)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/application.py", line 270, in initialize
    self.register_plugin_options()
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/main/application.py", line 150, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/plugins/manager.py", line 451, in register_options
    list(self.manager.map(register_and_enable))
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/plugins/manager.py", line 261, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/plugins/manager.py", line 447, in register_and_enable
    call_register_options(plugin)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/plugins/manager.py", line 357, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8/plugins/manager.py", line 207, in register_options
    add_options(optmanager)
  File "/home/xzise/.pyenv/versions/3.5.1/lib/python3.5/site-packages/flake8_quotes/__init__.py", line 38, in add_options
    parser.config_options.extend(['quotes', 'inline-quotes'])
```

More information:
* [List of plugins broken by 3.0.0](https://gitlab.com/pycqa/flake8/issues/149)
* [Guide to handle both versions](http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html#option-handling-on-flake8-2-and-3)

**Comment by twolfson** [comment]
Would you be interested in writing a PR to help us support both versions?

**Comment by twolfson** [comment]
This has been resolved by @xZise in #34 and released in `0.5.0`. Thanks for your help!

**Comment by twolfson** [comment]
`flake8==3.0.0` has finally been released and unfortunately we lost support by `flake8` dropping `pep8` from their code. As a result, this issue is no longer resolved.

**Comment by twolfson** [comment]
I believe @xZise mentioned this earlier but the fix should be as easy as:

http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html#standard-in-handling-on-flake8-2-5-2-6-and-3

**Comment by twolfson** [comment]
Actually, it looks like we would still need to do some weird `import` logic and the monkey patch is relatively simple so we can probably do it ourselves:

https://gitlab.com/pycqa/flake8-polyfill/blob/1.0.1/src/flake8_polyfill/stdin.py#L52-57

**Comment by twolfson** [comment]
I started working on this but have other obligations so I don't have time to finish =/ We will likely need to rework code to get compatibility in getting lines without `pep8`.

https://github.com/zheller/flake8-quotes/compare/master...twolfson:dev/fix.flake8.3

However, while reviewing the material it looks like Flake8 wants to add formatting support (which seems up this repo's alley). We should probably avoid maintaining compatibility and perform a full rewrite to get that support (so we maintain a `2.x.x` branch for a while).

http://flake8.pycqa.org/en/latest/plugin-development/formatters.html

**Comment by johnthagen** [comment]
I presume this is a related issue:

```...ImportError: No module named 'flake8.engine'...```

Full log:
```
$ python --version
Python 3.5.2
$ pip --version
pip 8.1.2 from /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (python 3.5)
install
0.95s$ pip install tox
Collecting tox
  Downloading tox-2.3.1-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 4.2MB/s 
Collecting virtualenv>=1.11.2 (from tox)
  Downloading virtualenv-15.0.2-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 888kB/s 
Collecting pluggy<0.4.0,>=0.3.0 (from tox)
  Downloading pluggy-0.3.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.17 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (from tox)
Installing collected packages: virtualenv, pluggy, tox
Successfully installed pluggy-0.3.1 tox-2.3.1 virtualenv-15.0.2
12.53s$ tox
GLOB sdist-make: /home/travis/build/johnthagen/stardust-rpg/setup.py
py35 create: /home/travis/build/johnthagen/stardust-rpg/.tox/py35
py35 installdeps: -rrequirements.txt, -rrequirements-dev.txt
py35 inst: /home/travis/build/johnthagen/stardust-rpg/.tox/dist/stardust-rpg-1.0.0.zip
py35 installed: aenum==1.4.5,beautifulsoup4==4.5.0,Django==1.9.8,django-enumfields==0.8.1,django-widget-tweaks==1.4.1,exitstatus==1.0.0,flake8==3.0.0,flake8-import-order==0.8,flake8-quotes==0.7.0,mccabe==0.5.0,pep8==1.7.0,pep8-naming==0.4.1,pycodestyle==2.0.0,pyflakes==1.2.3,requests==2.10.0,six==1.10.0,stardust-rpg==1.0.0
py35 runtests: PYTHONHASHSEED='3245833630'
py35 runtests: commands[0] | flake8
Traceback (most recent call last):
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/plugins/manager.py", line 159, in load_plugin
    self._load(verify_requirements)
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/plugins/manager.py", line 137, in _load
    self._plugin = resolve()
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8_quotes/__init__.py", line 5, in <module>
    from flake8.engine import pep8
ImportError: No module named 'flake8.engine'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".tox/py35/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/main/application.py", line 299, in run
    self._run(argv)
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/main/application.py", line 285, in _run
    self.initialize(argv)
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/main/application.py", line 275, in initialize
    self.find_plugins()
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/main/application.py", line 143, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/plugins/manager.py", line 369, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/plugins/manager.py", line 261, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/plugins/manager.py", line 367, in load_plugin
    return plugin.load_plugin()
  File "/home/travis/build/johnthagen/stardust-rpg/.tox/py35/lib/python3.5/site-packages/flake8/plugins/manager.py", line 167, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "flake8_quotes" due to No module named 'flake8.engine'.
ERROR: InvocationError: '/home/travis/build/johnthagen/stardust-rpg/.tox/py35/bin/flake8'
```

**Comment by xZise** [comment]
@johnthagen Indeed that is how the issue presents itself.
@twolfson As mentioned in #38 we could just use `flake8-polyfill` to avoid any testing logic:

```
from flake8_polyfill import stdin

stdin.monkey_patch('pep8')
```

There `pep8.stdin_get_value` will return then either `pep8`, `pycodestyle` or `flake8.utils`. Maybe I'm going to provide a merge request for that which directly returns the `stdin_get_value` without needing it to be patched, so something like this:

```
from flake8_polyfill.stdin import stdin_get_value
```

And also as mentioned in #38 as a workaround we could just wrap the import in `try-except` and just don't support `stdin` for now in Flake8 3.x.

**Comment by xZise** [comment]
Okay I overlooked that it uses `pep8` also to read the content of the file. And unfortunately `flake8.utils` has no real replacement for it. As an alternative we could do use `flake8_polyfill.version` to check if the version is below 2.6 and then import `pep8` and otherwise import `pycodestyle` (named as `pep8`).

**Comment by twolfson** [comment]
I think it would be a better usage of our time to stop trying to maintain compatibility for `2.x.x` and `3.x.x` in the same file. We should move the existing `flake8-quotes` iteration to a `0.x.x` branch and update the repo to only support `flake8==3` in a `1.x.x` version.

**Comment by xZise** [comment]
I don't think this will help much, as I think that Flake8 2.x will be used for quite some time and apart from the options thing (which is already solved) and this stdin it seems to work. I've a relatively simple patch based on my last comment (which again wasn't complete as I forgot that using `pycodestyle` in Flake8 3.x doesn't work). I'm going to provide it as a PR and it's up to you what you want to do with it.

**Comment by xZise** [comment]
Also you got a bit mixed up: The formatting logic is how it outputs the error. There is a “fixup logic” called “listener”, but I don't know how they work. It doesn't really seem to be documented.

**Comment by twolfson** [comment]
With respect to formatter: Ah, I see. Thanks for the clarification =) I guess we will wait until "listeners" get more documentation rather than using an undocumented/potentially volatile feature

**Comment by twolfson** [comment]
This should be resolved for good. This has been resolved in `0.8.1` via #44 and #46

**Comment by johnthagen** [comment]
@twolfson Perhaps not fully solved?

```bat
C:\Users\John Hagen\PycharmProjects\stardust-rpg>tox
GLOB sdist-make: C:\Users\John Hagen\PycharmProjects\stardust-rpg\setup.py
py35 create: C:\Users\John Hagen\PycharmProjects\stardust-rpg\.tox\py35
py35 installdeps: -rrequirements.txt, -rrequirements-dev.txt
py35 inst: C:\Users\John Hagen\PycharmProjects\stardust-rpg\.tox\dist\stardust-rpg-1.0.0.zip
py35 installed: aenum==1.4.5,beautifulsoup4==4.5.0,Django==1.9.8,django-enumfields==0.8.1,django-widget-tweaks==1.4.1,exitstatus==1.0.0,flake8==3.0.1,flake8-import-order==0.9,flake8-quotes==0.8.1,mccabe==0.5.0,pep8-naming==0.4.1,pycodestyle==2.0.0,pyflakes==1.2.3,requests==2.10.0,six==1.10.0,stardust-rpg==1.0.0
py35 runtests: PYTHONHASHSEED='750'
py35 runtests: commands[0] | flake8
Process Process-1:
Traceback (most recent call last):
  File "c:\python35\Lib\multiprocessing\process.py", line 254, in _bootstrap
    self.run()
  File "c:\python35\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 564, in run_checks
    self.run_ast_checks()
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 475, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8_quotes\__init__.py", line 97, in run
    for error in errors:
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8_quotes\__init__.py", line 125, in get_quotes_errors
    if not unprefixed_string.startswith(self.inline_quotes['bad_single']):
AttributeError: 'QuoteChecker' object has no attribute 'inline_quotes'
Process Process-2:
Traceback (most recent call last):
  File "c:\python35\Lib\multiprocessing\process.py", line 254, in _bootstrap
    self.run()
  File "c:\python35\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 564, in run_checks
    self.run_ast_checks()
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 475, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8_quotes\__init__.py", line 97, in run
    for error in errors:
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8_quotes\__init__.py", line 125, in get_quotes_errors
    if not unprefixed_string.startswith(self.inline_quotes['bad_single']):
AttributeError: 'QuoteChecker' object has no attribute 'inline_quotes'
Process Process-3:
Traceback (most recent call last):
  File "c:\python35\Lib\multiprocessing\process.py", line 254, in _bootstrap
    self.run()
  File "c:\python35\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 564, in run_checks
    self.run_ast_checks()
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 475, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8_quotes\__init__.py", line 97, in run
    for error in errors:
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8_quotes\__init__.py", line 125, in get_quotes_errors
    if not unprefixed_string.startswith(self.inline_quotes['bad_single']):
AttributeError: 'QuoteChecker' object has no attribute 'inline_quotes'
Process Process-4:
Traceback (most recent call last):
  File "c:\python35\Lib\multiprocessing\process.py", line 254, in _bootstrap
    self.run()
  File "c:\python35\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 564, in run_checks
    self.run_ast_checks()
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8\checker.py", line 475, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8_quotes\__init__.py", line 97, in run
    for error in errors:
  File "c:\users\johnha~1\pychar~2\stardu~1\tox~1\py35\lib\site-packages\flake8_quotes\__init__.py", line 125, in get_quotes_errors
    if not unprefixed_string.startswith(self.inline_quotes['bad_single']):
AttributeError: 'QuoteChecker' object has no attribute 'inline_quotes'
```

**Comment by xZise** [comment]
It looks like this is not properly initializing the plugin. Can you provide a minimal example which still shows this happening so that we can reproduce it? As it seems Flake8 never calls `QuoteChecker.parse_options` which actually sets `self.inline_quotes`.

You could also try to explicitly specify the `--inline-quotes` parameter. Either directly to Flake8 (make sure it's properly quoted) or to something like the `[flake8]` section in `setup.cfg` or `tox.ini`. Although it shouldn't make a difference because just calling it should suffice.

**Comment by twolfson** [comment]
@johnthagen I believe that's linked to this issue https://github.com/zheller/flake8-quotes/pull/42#issuecomment-234782045 . Can you try using `flake8==2` and seeing if the problem persists?

**Comment by johnthagen** [comment]
@twolfson Here is as link to working build with `flake8==2.6.2`: https://travis-ci.org/johnthagen/stardust-rpg/builds/147585802

This was after I reverted my `requirements-dev.txt` to  `flake8==2.6.2`: https://github.com/johnthagen/stardust-rpg/blob/master/requirements-dev.txt

I'll try to create a minimal example for you later today.

**Comment by twolfson** [comment]
I'm going to try reproducing the error on your repo now, thanks for linking =)

**Comment by twolfson** [comment]
I attempted to reproduce on your repo but was unable to. I checked out the last failing commit in Travis CI and installed its dependencies but it didn't fail locally =/

https://travis-ci.org/johnthagen/stardust-rpg/builds/147339395

**Comment by johnthagen** [comment]
@twolfson @xZise 

I think it's a Windows specific issue, Travis is running fine with the latest `flake8` and `flake8-quotes`.

https://travis-ci.org/johnthagen/stardust-rpg/builds/147887298

```
$ python --version
Python 3.5.2
$ pip --version
pip 8.1.2 from /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (python 3.5)
install
0.93s$ pip install tox
Collecting tox
  Downloading tox-2.3.1-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 4.2MB/s 
Collecting virtualenv>=1.11.2 (from tox)
  Downloading virtualenv-15.0.2-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 872kB/s 
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.17 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (from tox)
Collecting pluggy<0.4.0,>=0.3.0 (from tox)
  Downloading pluggy-0.3.1-py2.py3-none-any.whl
Installing collected packages: virtualenv, pluggy, tox
Successfully installed pluggy-0.3.1 tox-2.3.1 virtualenv-15.0.2
16.52s$ tox
GLOB sdist-make: /home/travis/build/johnthagen/stardust-rpg/setup.py
py35 create: /home/travis/build/johnthagen/stardust-rpg/.tox/py35
py35 installdeps: -rrequirements.txt, -rrequirements-dev.txt
py35 inst: /home/travis/build/johnthagen/stardust-rpg/.tox/dist/stardust-rpg-1.0.0.zip
py35 installed: aenum==1.4.5,beautifulsoup4==4.5.0,Django==1.9.8,django-enumfields==0.8.1,django-widget-tweaks==1.4.1,exitstatus==1.0.0,flake8==3.0.2,flake8-import-order==0.9.1,flake8-quotes==0.8.1,mccabe==0.5.0,pep8-naming==0.4.1,pycodestyle==2.0.0,pyflakes==1.2.3,requests==2.10.0,six==1.10.0,stardust-rpg==1.0.0
py35 runtests: PYTHONHASHSEED='1372435827'
py35 runtests: commands[0] | flake8
___________________________________ summary ____________________________________
  py35: commands succeeded
  congratulations :)
```

But on my Windows 10 machine I am having problems even getting `flake8` working: https://gitlab.com/pycqa/flake8/issues/197

When I get `flake8` itself working reliably again (probably the next release) I'll check in to make sure `flake8-quotes` is working on Windows.

**Comment by twolfson** [comment]
Ah, k. I don't have time to attempt to triage this again. I will take a look by the end of next week.

**Comment by johnthagen** [comment]
@twolfson I'd like to tentatively say that `flake8-quotes` does not have any issues on Windows, but it lies with `flake8` 3.0.2.

The problem seems to be: https://gitlab.com/pycqa/flake8/issues/179

All the below testing is with `flake8` 3.0.2 and `flake8-quotes` 0.8.1 on Windows 10.

If I run without `flake8-quotes` installed,

```
flake8
Process Process-1:
Traceback (most recent call last):
  File "c:\python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "c:\python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python35\lib\site-packages\flake8\checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "c:\python35\lib\site-packages\flake8\checker.py", line 564, in run_checks
    self.run_ast_checks()
  File "c:\python35\lib\site-packages\flake8\checker.py", line 468, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "c:\python35\lib\site-packages\flake8\checker.py", line 448, in run_check
    return plugin.execute(**arguments)
  File "c:\python35\lib\site-packages\flake8\plugins\manager.py", line 126, in execute
    return self.plugin(*args, **kwargs)  # pylint: disable=not-callable
  File "c:\python35\lib\site-packages\flake8\plugins\pyflakes.py", line 53, in __init__
    with_doctest = self.with_doctest
AttributeError: 'FlakesChecker' object has no attribute 'with_doctest'
... stopped while processing files
```
I get the above error mentioned in that issue.

If I run without `flake8-quotes` installed
```
flake8 --jobs=1
```
It executes correctly.

If I run with `flake8-quotes` installed:
```
flake8
Process Process-1:
Traceback (most recent call last):
  File "c:\python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "c:\python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python35\lib\site-packages\flake8\checker.py", line 222, in _run_checks_from_queue
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "c:\python35\lib\site-packages\flake8\checker.py", line 564, in run_checks
    self.run_ast_checks()
  File "c:\python35\lib\site-packages\flake8\checker.py", line 475, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "c:\python35\lib\site-packages\flake8_quotes\__init__.py", line 97, in run
    for error in errors:
  File "c:\python35\lib\site-packages\flake8_quotes\__init__.py", line 125, in get_quotes_errors
    if not unprefixed_string.startswith(self.inline_quotes['bad_single']):
AttributeError: 'QuoteChecker' object has no attribute 'inline_quotes'
... stopped while processing files
```

If I run with `flake8-quotes` installed:
```
flake8 --jobs=1
```
everything works fine.  So it seems this concurrency bug in `flake8` 3.0.0+ is the root of the issue and it happens to manifest differently when `flake8-quotes` is installed.  I wouldn't spend any more effort on it until `flake8` is fixed for Windows.

**Comment by twolfson** [comment]
Ah, k. Thanks for doing the research into this issue =) Closing this issue for now

**Comment by johnthagen** [comment]
@twolfson Confirmed that `flake8` 3.0.3 resolves this issue on Windows.

**Comment by xZise** [comment]
Well [3.0.3](http://flake8.pycqa.org/en/latest/release-notes/3.0.3.html) disabled any concurrent processing, so it's the same as using `--jobs=1` on pre 3.0.3. But afaik there is nothing this plugin can do for 3.0.0-3.0.2 (apart from the fact that 3.0.3 also fixes #47). (So this comment was more just for your information)
